POST http://localhost:8080/category
Content-Type: application/json
X-Token:d77bd5f8-62a4-4d46-990a-5e8c30f1c554

{
  "name": "dog"
}

###
POST http://localhost:8080/category
Content-Type: application/json
X-Token:d77bd5f8-62a4-4d46-990a-5e8c30f1c554

{
  "name": "cat"
}

###

POST http://localhost:8080/tag
Content-Type: application/json
X-Token:d77bd5f8-62a4-4d46-990a-5e8c30f1c554

{
  "name": "health"
}

###

POST http://localhost:8080/tag
Content-Type: application/json
X-Token:d77bd5f8-62a4-4d46-990a-5e8c30f1c554

{
  "name": "cat"
}

###

POST http://localhost:8080/tag
Content-Type: application/json
X-Token:d77bd5f8-62a4-4d46-990a-5e8c30f1c554

{
  "name": "dog"
}

###

POST http://localhost:8080/tag
Content-Type: application/json
X-Token:d77bd5f8-62a4-4d46-990a-5e8c30f1c554

{
  "name": "friend"
}

###

POST http://localhost:8080/tag
Content-Type: application/json
X-Token:d77bd5f8-62a4-4d46-990a-5e8c30f1c554

{
  "name": "good"
}

###
POST http://localhost:8080/pet
Content-Type: application/json
X-Token:d77bd5f8-62a4-4d46-990a-5e8c30f1c554


{
  "category": {
    "id": 1
  },
  "name": "Baddy",
  "tags": [
    {
      "id": 2
    },
    {
      "id": 4
    }
  ],
  "petStatus":"AVAILABLE"
}
###


POST http://localhost:8080/pet
Content-Type: application/json
X-Token:d77bd5f8-62a4-4d46-990a-5e8c30f1c554

{
  "category": {
    "id": 2
  },
  "name": "Teddy",
  "tags": [
    {
      "id": 1
    },
    {
      "id": 3
    }
  ],
  "petStatus":"PENDING"
}
###
POST http://localhost:8080/pet
Content-Type: application/json
X-Token:d77bd5f8-62a4-4d46-990a-5e8c30f1c554

{
  "category": {
    "id": 1
  },
  "name": "Dandy",
  "tags": [
    {
      "id": 2
    },
    {
      "id": 3
    }
  ],
  "petStatus":"SOLD"
}
###

POST http://localhost:8080/pet
Content-Type: application/json
X-Token:d77bd5f8-62a4-4d46-990a-5e8c30f1c554

{
  "category": {
    "id": 1
  },
  "name": "Barry",
  "tags": [
    {
      "id": 1
    },
    {
      "id": 2
    },
    {
      "id": 4
    }
  ],
  "petStatus":"PENDING"
}

###
GET http://localhost:8080/pet/1
Content-Type: application/json
X-Token:d77bd5f8-62a4-4d46-990a-5e8c30f1c554
###

DELETE http://localhost:8080/pet/1
Content-Type: application/json
X-Token:d77bd5f8-62a4-4d46-990a-5e8c30f1c554

###
GET http://localhost:8080/pet/findByStatus?status=sold
Content-Type: application/json
X-Token:d77bd5f8-62a4-4d46-990a-5e8c30f1c554
###
PUT http://localhost:8080/pet
Content-Type: application/json
X-Token:d77bd5f8-62a4-4d46-990a-5e8c30f1c554

{
  "id": 2,
  "category": {
    "id": 1
  },
  "name": "Changed",
  "tags": [
    {
      "id": 2
    },
    {
      "id": 1
    },
    {
      "id": 4
    }
  ],
  "petStatus":"SOLD"
}
###

POST http://localhost:8080/store/order
Content-Type: application/json
X-Token:d77bd5f8-62a4-4d46-990a-5e8c30f1c554

{
  "id": 0,
  "petId": 2,
  "quantity": 1,
  "shipDate": "",
  "orderStatus": "DELIVERED",
  "complete": true

}
###

GET http://localhost:8080/store/inventory
Content-Type: application/json
X-Token:d77bd5f8-62a4-4d46-990a-5e8c30f1c554

###

GET http://localhost:8080/store/order/1
Content-Type: application/json
X-Token:d77bd5f8-62a4-4d46-990a-5e8c30f1c554

###

DELETE http://localhost:8080/store/order/1
Content-Type: application/json
X-Token:d77bd5f8-62a4-4d46-990a-5e8c30f1c554

###
GET http://localhost:8080/store/order/1
###
POST http://localhost:8080/user
Content-Type: application/json

{
  "id": 0,
  "username": "petr811",
  "firstName": "Pyotr",
  "lastName": "Shamburov",
  "email": "petro-92@mail.ru",
  "password": "1234",
  "phones": ["+3752523455675",
    "802951177302"],
  "address": {
    "country": "Belarus",
    "city": "Minsk",
    "street": "Test",
    "houseNumber": 23,
    "postIndex": 220340
  },
  "userStatus": 1,
  "role": "ADMIN"
}

###

POST http://localhost:8080/user
Content-Type: application/json

{
  "id": 0,
  "username": "Ivavtr",
  "firstName": "Ivan",
  "lastName": "Ivanov",
  "email": "iva-92@mail.ru",
  "password": "1234",
  "phones": ["+3752523455675",
    "802951177302"],
  "address": {
    "country": "Belarus",
    "city": "Minsk",
    "street": "ttyjf",
    "houseNumber": 23,
    "postIndex": 220340
  },
  "userStatus": 2,
  "role": "ADMIN"
}

###

PUT http://localhost:8080/user/petr811
Content-Type: application/json

{
  "id": 0,
  "username": "Test",
  "firstName": "Test",
  "lastName": "Test",
  "email": "iva-34@mail.com",
  "password": "1234",
  "phone": ["80295145673",
  "234526636",
  "3463473477"],
  "address": {
    "country": "Russia",
    "city": "Moscow",
    "street": "test",
    "houseNumber": 29,
    "postIndex": 220320
  },
  "userStatus": 1,
  "role": "ADMIN"
}

###
POST http://localhost:8080/user
Content-Type: application/json

{
  "id": 0,
  "username": "Martin",
  "firstName": "Mark",
  "lastName": "Ivanov",
  "email": "iva-34@mail.com",
  "password": "1234",
  "phone": "80295145673",
  "userStatus": 4,
  "role": "USER"

}
###
POST http://localhost:8080/user
Content-Type: application/json

{
  "id": 0,
  "username": "Nik124",
  "firstName": "Nike",
  "lastName": "Ivanov",
  "email": "iva-34@mail.com",
  "password": "1234",
  "phone": "80295145673",
  "userStatus": 1,
  "role": "USER"
}
###
GET http://localhost:8080/user/Test
Content-Type: application/json

###

DELETE http://localhost:8080/user/Nik124
Content-Type: application/json

###

POST http://localhost:8080/user/auth
Content-Type: application/json

{
"username": "petr811",
  "password": "1234"
}

###